#!/usr/bin/env python
#
# This file is part of antiSMASH.
#
# antiSMASH is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# antiSMASH is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with antiSMASH.  If not, see <http://www.gnu.org/licenses/>.
"""Watch the status directory for status updates from jobs
"""
import os
from os import path
import time
from argparse import ArgumentParser
from datetime import datetime
from dispatcher.storage import get_storage
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

version = "0.0.2"

class EventHandler(FileSystemEventHandler):
    """Event handler to track file modifications in the status directory"""

    def __init__(self, redis_store):
        self.redis_store = redis_store

    def get_job_id(self, event):
        return path.basename(event.src_path)

    def on_created(self, event):
        if not event.is_directory:
            print(f"New job '{self.get_job_id(event)}' created")

    def on_deleted(self, event):
        if not event.is_directory:
            print(f"Removing job '{self.get_job_id(event)}'")

    def on_modified(self, event):
        if not event.is_directory:
            jobid = f'job:{self.get_job_id(event)}'
            try:
                with open(event.src_path, 'r') as fh:
                    status = fh.readline().strip()
                    self.redis_store.hset(jobid, 'status', status)
                    self.redis_store.hset(jobid, 'last_changed', datetime.utcnow().isoformat())
            except IOError as e:
                print(f"Failed to get info for '{jobid}': {e}")

def main():
    """Parse command line, set up the database, start the event loop"""
    default_queue = os.getenv('AS_QUEUE', "redis://localhost:6379/0")
    parser = ArgumentParser()
    parser.add_argument('-q', '--queue', dest="queue",
                        help="URI of the database containing the job queue (default: %(default)s)",
                        default=default_queue)
    parser.add_argument('-s', '--statusdir', dest="statusdir",
                        default="/tmp/antismash_status",
                        help="Directory to keep job status files in (default: %(default)s)")
    options = parser.parse_args()

    redis_store = get_storage(options.queue)
    if not path.isdir(options.statusdir):
        os.makedirs(options.statusdir)

    event_handler = EventHandler(redis_store)
    observer = Observer()
    observer.schedule(event_handler, options.statusdir, recursive=True)
    observer.start()

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()

if __name__ == "__main__":
    main()
